### ISSUE TITLE
Runtime Exception in Graph Decision Example

### ISSUE THREAD

**Issue by mreposa** [p2t2/figaro#516]
I see this error running this example under Figaro 3.3 and 4.0:

Running MH Before...
Computing Optimal Decision...
java.lang.NullPointerException
        at com.cra.figaro.example.graph.dGraphGen$$anonfun$addGraph$1.apply(dGraphGen.scala:38)
        at com.cra.figaro.example.graph.dGraphGen$$anonfun$addGraph$1.apply(dGraphGen.scala:38)
        at scala.collection.immutable.List.map(List.scala:277)
        at com.cra.figaro.example.graph.dGraphGen$.addGraph(dGraphGen.scala:38)
        at com.cra.figaro.example.graph.dGraphGen$$anonfun$4.apply(dGraphGen.scala:56)
        at com.cra.figaro.example.graph.dGraphGen$$anonfun$4.apply(dGraphGen.scala:56)
        at com.cra.figaro.language.Apply2.generateValue(Apply.scala:57)
        at com.cra.figaro.language.Deterministic.generateValue(Deterministic.scala:31)
        at com.cra.figaro.language.Deterministic.generateValue(Deterministic.scala:20)
        at com.cra.figaro.algorithm.sampling.MetropolisHastings.attemptChange(MetropolisHastings.scala:80)
        at com.cra.figaro.algorithm.sampling.MetropolisHastings.updateOne(MetropolisHastings.scala:206)
        at com.cra.figaro.algorithm.sampling.MetropolisHastings.updateMany(MetropolisHastings.scala:228)
        at com.cra.figaro.algorithm.sampling.MetropolisHastings.proposeAndUpdate(MetropolisHastings.scala:248)
        at com.cra.figaro.algorithm.sampling.MetropolisHastings.mhStep(MetropolisHastings.scala:324)
        at com.cra.figaro.algorithm.sampling.MetropolisHastings$$anonfun$doInitialize$2.apply(MetropolisHastings.scala:361)
        at com.cra.figaro.algorithm.sampling.MetropolisHastings$$anonfun$doInitialize$2.apply(MetropolisHastings.scala:361)
        at scala.collection.immutable.Range.foreach(Range.scala:166)
        at com.cra.figaro.algorithm.sampling.MetropolisHastings.doInitialize(MetropolisHastings.scala:361)
        at com.cra.figaro.algorithm.decision.OneTimeDecisionMetropolisHastings.run(DecisionMetropolisHastings.scala:164)
        at com.cra.figaro.algorithm.OneTime$class.doStart(OneTime.scala:28)
        at com.cra.figaro.algorithm.decision.OneTimeDecisionMetropolisHastings.doStart(DecisionMetropolisHastings.scala:150)
        at com.cra.figaro.algorithm.Algorithm$class.start(Algorithm.scala:83)
        at com.cra.figaro.algorithm.sampling.BaseUnweightedSampler.start(UnweightedSampler.scala:26)
        at com.cra.figaro.example.graph.GraphDecision$.main(GraphDecision.scala:96)
        at com.cra.figaro.example.graph.GraphDecision.main(GraphDecision.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at scala.reflect.internal.util.ScalaClassLoader$$anonfun$run$1.apply(ScalaClassLoader.scala:70)
        at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
        at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:101)
        at scala.reflect.internal.util.ScalaClassLoader$class.run(ScalaClassLoader.scala:70)
        at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:101)
        at scala.tools.nsc.CommonRunner$class.run(ObjectRunner.scala:22)
        at scala.tools.nsc.ObjectRunner$.run(ObjectRunner.scala:39)
        at scala.tools.nsc.CommonRunner$class.runAndCatch(ObjectRunner.scala:29)
        at scala.tools.nsc.ObjectRunner$.runAndCatch(ObjectRunner.scala:39)
        at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:65)
        at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:87)
        at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:98)
        at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:103)
        at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)

**Comment by bruttenberg** [comment]
I think I have a fix for this bug but I'm not sure. I can't reproduce it on a smaller example, but the fix I have seems to make it work.

**Comment by mreposa** [comment]
I ran the example to completion last night, so I'm closing this one.
