### ISSUE TITLE
SelectableSet error in particle filter

### ISSUE THREAD

**Issue by apfeffer** [p2t2/figaro#525]
The following code produces an IndexOutOfRangeException in SelectableSet
--
import com.cra.figaro.language._
import com.cra.figaro.library.compound._
import com.cra.figaro.algorithm.filtering._
import com.cra.figaro.algorithm.sampling.Forward
import com.cra.figaro.algorithm.sampling.Importance

object PFTest {
  val length = 100

  def main(args: Array[String]) {
    test(false)
    test(true)
  }

  def trans(previous: Universe): Universe = {
    val u = Universe.createNew()
    val faulty = If(previous.get[Boolean]("faulty"), Flip(0.99), Flip(0.01))("faulty", u)
    val lowEfficiency = RichCPD(faulty, previous.get[Boolean]("lowEfficiency"),
      (*, OneOf(true)) -> Flip(0.9),
      (OneOf(true), *) -> Flip(0.9),
      (*, *) -> Flip(0.05))("lowEfficiency", u)
    val lowGauge = If(lowEfficiency, Flip(0.95), Flip(0.05))("lowGauge", u)
    u
  }

  def createObservationSequence(f: Boolean): Array[Boolean] = {
    Universe.createNew()
    val faulty: Array[Element[Boolean]] = Array.fill(length + 1)(Constant(false))
    val lowEfficiency: Array[Element[Boolean]] = Array.fill(length + 1)(Constant(false))
    val lowGauge: Array[Element[Boolean]] = Array.fill(length + 1)(Constant(false))
    faulty(0) = Flip(0.001)
    lowEfficiency(0) = Constant(false)
    for { i <- 1 to length } {
      faulty(i) = If(faulty(i-1), Constant(true), Constant(false))
      lowEfficiency(i) = RichCPD(faulty(i), lowEfficiency(i-1),
      (*, OneOf(true)) -> Flip(0.9),
      (OneOf(true), *) -> Flip(0.9),
      (*, *) -> Flip(0.05))
      lowGauge(i) = If(lowEfficiency(i), Flip(0.95), Flip(0.05))
    }
    faulty(0).observe(f)
    Importance(1)
    val result = Array.fill(length)(false)
    for { i <- 0 until length } { result(i) = lowGauge(i + 1).value }
    print("Observation sequence: ")
    for (i <- 0 until length) { if (result(i)) print('T') else print('F') }
    println()
    result
  }

  def test(f: Boolean) {
    val init = Universe.createNew()
    val faulty = Flip(0.001)("faulty", init)
    val lowEfficiency = Constant(false)("lowEfficiency", init)

    println("Faulty: " + f)
    val obsSeq = createObservationSequence(f)
    val pf = ParticleFilter(init, trans _, 10000)
    pf.start()
    println("Start: " + pf.currentProbability("faulty", true))
    for { i <- 0 until length } {
      pf.advanceTime(List(NamedEvidence("lowGauge", Observation(obsSeq(i)))))
      println("Step " + (i+1) + ": " + pf.currentProbability("faulty", true))
    }
    println("Result: " + pf.currentProbability("faulty", true))
    println()
  }
}
--
Here's the stack trace:

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 16
	at com.cra.figaro.util.HashSelectableSet.com$cra$figaro$util$HashSelectableSet$$resizeHelper(SelectableSet.scala:84)
	at com.cra.figaro.util.HashSelectableSet$$anonfun$resize$1.apply(SelectableSet.scala:91)
	at com.cra.figaro.util.HashSelectableSet$$anonfun$resize$1.apply(SelectableSet.scala:91)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at com.cra.figaro.util.HashSelectableSet.resize(SelectableSet.scala:91)
	at com.cra.figaro.util.HashSelectableSet.$plus$eq(SelectableSet.scala:110)
	at com.cra.figaro.util.HashSelectableSet.$plus$eq(SelectableSet.scala:37)
	at scala.collection.mutable.SetLike$class.add(SetLike.scala:82)
	at com.cra.figaro.util.HashSelectableSet.add(SelectableSet.scala:37)
	at com.cra.figaro.language.Universe.activate(Universe.scala:175)
	at com.cra.figaro.language.Element.<init>(Element.scala:480)
	at com.cra.figaro.language.AtomicFlip.<init>(Flip.scala:39)
	at com.cra.figaro.language.Flip$.apply(Flip.scala:98)
	at exercises.PFTest$$anonfun$5.apply(PFTest.scala:24)
	at exercises.PFTest$$anonfun$5.apply(PFTest.scala:24)
	at com.cra.figaro.library.compound.If$$anonfun$$lessinit$greater$2.apply(If.scala:33)
	at com.cra.figaro.library.compound.If$$anonfun$$lessinit$greater$2.apply(If.scala:33)
	at com.cra.figaro.language.Chain.getResult(Chain.scala:66)
	at com.cra.figaro.language.Chain.get(Chain.scala:56)
	at com.cra.figaro.library.cache.PermanentCache.doCachingChain(PermanentCache.scala:64)
	at com.cra.figaro.library.cache.PermanentCache.apply(PermanentCache.scala:43)
	at com.cra.figaro.algorithm.sampling.LikelihoodWeighter.traverse(LikelihoodWeighter.scala:110)
	at com.cra.figaro.algorithm.sampling.LikelihoodWeighter.computeWeight(LikelihoodWeighter.scala:50)
	at com.cra.figaro.algorithm.filtering.ParticleFilter$class.makeWeightedParticle(ParticleFilter.scala:85)
	at com.cra.figaro.algorithm.filtering.OneTimeParticleFilter.makeWeightedParticle(ParticleFilter.scala:179)
	at com.cra.figaro.algorithm.filtering.ParticleFilter$class.addWeightedParticle(ParticleFilter.scala:125)
	at com.cra.figaro.algorithm.filtering.OneTimeParticleFilter.addWeightedParticle(ParticleFilter.scala:179)
	at com.cra.figaro.algorithm.filtering.OneTimeParticleFilter$$anonfun$advanceTime$1.apply(ParticleFilter.scala:210)
	at com.cra.figaro.algorithm.filtering.OneTimeParticleFilter$$anonfun$advanceTime$1.apply(ParticleFilter.scala:210)
	at com.cra.figaro.algorithm.filtering.OneTimeParticleFilter$$anonfun$7.apply(ParticleFilter.scala:186)
	at com.cra.figaro.algorithm.filtering.OneTimeParticleFilter$$anonfun$7.apply(ParticleFilter.scala:186)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.immutable.Range.foreach(Range.scala:160)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at com.cra.figaro.algorithm.filtering.OneTimeParticleFilter.doTimeStep(ParticleFilter.scala:186)
	at com.cra.figaro.algorithm.filtering.OneTimeParticleFilter.advanceTime(ParticleFilter.scala:210)
	at exercises.PFTest$$anonfun$test$1.apply$mcVI$sp(PFTest.scala:64)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
	at exercises.PFTest$.test(PFTest.scala:63)
	at exercises.PFTest$.main(PFTest.scala:13)
	at exercises.PFTest.main(PFTest.scala)

**Comment by apfeffer** [comment]
Another time, it produced the following exception in directContextContents.

Other times it runs fine.

Exception in thread "main" java.util.NoSuchElementException
	at com.cra.figaro.language.Element.directContextContents(Element.scala:163)
	at com.cra.figaro.language.Element.clearContext(Element.scala:178)
	at com.cra.figaro.language.Universe$$anonfun$clearTemporaries$1.apply(Universe.scala:242)
	at com.cra.figaro.language.Universe$$anonfun$clearTemporaries$1.apply(Universe.scala:242)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at com.cra.figaro.language.Universe.clearTemporaries(Universe.scala:242)
	at com.cra.figaro.algorithm.filtering.ParticleFilter$class.makeWeightedParticle(ParticleFilter.scala:93)
	at com.cra.figaro.algorithm.filtering.OneTimeParticleFilter.makeWeightedParticle(ParticleFilter.scala:179)
	at com.cra.figaro.algorithm.filtering.ParticleFilter$class.addWeightedParticle(ParticleFilter.scala:125)
	at com.cra.figaro.algorithm.filtering.OneTimeParticleFilter.addWeightedParticle(ParticleFilter.scala:179)
	at com.cra.figaro.algorithm.filtering.OneTimeParticleFilter$$anonfun$advanceTime$1.apply(ParticleFilter.scala:210)
	at com.cra.figaro.algorithm.filtering.OneTimeParticleFilter$$anonfun$advanceTime$1.apply(ParticleFilter.scala:210)
	at com.cra.figaro.algorithm.filtering.OneTimeParticleFilter$$anonfun$7.apply(ParticleFilter.scala:186)
	at com.cra.figaro.algorithm.filtering.OneTimeParticleFilter$$anonfun$7.apply(ParticleFilter.scala:186)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.immutable.Range.foreach(Range.scala:160)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at com.cra.figaro.algorithm.filtering.OneTimeParticleFilter.doTimeStep(ParticleFilter.scala:186)
	at com.cra.figaro.algorithm.filtering.OneTimeParticleFilter.advanceTime(ParticleFilter.scala:210)
	at exercises.PFTest$$anonfun$test$1.apply$mcVI$sp(PFTest.scala:64)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
	at exercises.PFTest$.test(PFTest.scala:63)
	at exercises.PFTest$.main(PFTest.scala:13)
	at exercises.PFTest.main(PFTest.scala)

**Comment by apfeffer** [comment]
If I put the internal Flips in the definition of faulty explicitly inside the new universe, it works.

    val faulty = If(previous.get[Boolean]("faulty"), Flip(0.99)("", u), Flip(0.01)("", u))("faulty", u)

This is strange because they should be put into that universe anyway because I just called universe.createNew().

**Comment by bruttenberg** [comment]
I’m not sure this is the problem, but If does call by value name now right? So it’s possible that by the time that the If conditions get executed, the universe has changed.

+  +  +  +  +  +  +  +  +  +  +  +  +  +
Brian Ruttenberg, PhD
Senior Scientist
Decision Management Systems Division
Government Services
Charles River Analytics Inc.
617.491.3474 x730
www.cra.com<http://www.cra.com/>

**Comment by apfeffer** [comment]
Right, that’s the problem!

Yuck, this is awful to have to debug! Is there any solution? Maybe, in a chain, store the universe of the chain and make sure the elements created when the chain is expanded go in that universe.

+  +  +  +  +  +  +  +  +  +  +  +
Avi Pfeffer
Charles River Analytics Inc.
apfeffer@cra.com<mailto:apfeffer@cra.com>
(617) 491-3474x513

**Comment by bruttenberg** [comment]
That’s a good question and possible answer. Is there ever a legitimate reason why you would create an element inside a chain but place the element in a different universe than the chain?

Seems like the answer is no to me.

+  +  +  +  +  +  +  +  +  +  +  +  +  +
Brian Ruttenberg, PhD
Senior Scientist
Decision Management Systems Division
Government Services
Charles River Analytics Inc.
617.491.3474 x730
www.cra.com<http://www.cra.com/>

**Comment by apfeffer** [comment]
I can’t imagine it. I don’t know what the semantics would be if the elements inside a chain were in a different universe.

+  +  +  +  +  +  +  +  +  +  +  +
Avi Pfeffer
Charles River Analytics Inc.
apfeffer@cra.com<mailto:apfeffer@cra.com>
(617) 491-3474x513

**Comment by bruttenberg** [comment]
Well, we could try to put something in that automatically makes the universes match. I don’t think the fix is trivial though, since that implicit universe might cause some problems.


+  +  +  +  +  +  +  +  +  +  +  +  +  +
Brian Ruttenberg, PhD
Senior Scientist
Decision Management Systems Division
Government Services
Charles River Analytics Inc.
617.491.3474 x730
www.cra.com<http://www.cra.com/>

**Comment by apfeffer** [comment]
Here’s a possible fix: When expanding a chain, set the implicit universe to the universe of the chain. Then set it back when you’re done expanding.

+  +  +  +  +  +  +  +  +  +  +  +
Avi Pfeffer
Charles River Analytics Inc.
apfeffer@cra.com<mailto:apfeffer@cra.com>
(617) 491-3474x513
