### ISSUE TITLE
OutOfMemoryError in Simple Learning Example

### ISSUE THREAD

**Issue by mreposa** [p2t2/figaro#538]
I’m getting an OutOfMemoryError running the Simple Learning Figaro Example. I have run this example many times in the past and have never seen this error until recently. The output is below:

Running SimpleLearning
03:02 PM
True model:
Error: MH sampler did not accept any samples
Error: MH sampler did not accept any samples
Error: MH sampler did not accept any samples
Error: MH sampler did not accept any samples
Error: MH sampler did not accept any samples
Error: MH sampler did not accept any samples
Error: MH sampler did not accept any samples
Error: MH sampler did not accept any samples
Error: MH sampler did not accept any samples
Error: MH sampler did not accept any samples
Error: MH sampler did not accept any samples
Error: MH sampler did not accept any samples
Error: MH sampler did not accept any samples
100 training examples, scale = 100
Learning:
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at scala.collection.immutable.Map$Map2.updated(Map.scala:130)
        at scala.collection.immutable.Map$Map2.$plus(Map.scala:131)
        at scala.collection.immutable.MapLike$$anonfun$$plus$plus$1.apply(MapLike.scala:88)
        at scala.collection.immutable.MapLike$$anonfun$$plus$plus$1.apply(MapLike.scala:88)
        at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:142)
        at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:142)
        at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:322)
        at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:978)
        at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:978)
        at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:142)
        at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104)
        at scala.collection.TraversableOnce$class.$div$colon(TraversableOnce.scala:136)
        at scala.collection.AbstractTraversable.$div$colon(Traversable.scala:104)
        at scala.collection.immutable.MapLike$class.$plus$plus(MapLike.scala:88)
        at scala.collection.immutable.AbstractMap.$plus$plus(Map.scala:194)
        at com.cra.figaro.algorithm.factored.factors.SufficientStatisticsSemiring.mapProduct(SufficientStatisticsSemirin
g.scala:68)
        at com.cra.figaro.algorithm.factored.factors.SufficientStatisticsSemiring.product(SufficientStatisticsSemiring.s
cala:47)
        at com.cra.figaro.algorithm.factored.factors.SufficientStatisticsSemiring.product(SufficientStatisticsSemiring.s
cala:27)
        at com.cra.figaro.algorithm.factored.factors.BasicFactor$$anonfun$product$1.apply(BasicFactor.scala:101)
        at com.cra.figaro.algorithm.factored.factors.SparseFactor$$anonfun$combination$4$$anonfun$apply$6.apply(SparseFa
ctor.scala:140)
        at com.cra.figaro.algorithm.factored.factors.SparseFactor$$anonfun$combination$4$$anonfun$apply$6.apply(SparseFa
ctor.scala:133)
        at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:778)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:777)
        at com.cra.figaro.algorithm.factored.factors.SparseFactor$$anonfun$combination$4.apply(SparseFactor.scala:133)
        at com.cra.figaro.algorithm.factored.factors.SparseFactor$$anonfun$combination$4.apply(SparseFactor.scala:121)
        at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:778)
        at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:221)
        at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:428)
        at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:428)
        at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:777)
        at com.cra.figaro.algorithm.factored.factors.SparseFactor.combination(SparseFactor.scala:121)
03:07 PM

**Comment by apfeffer** [comment]
@mreposa Has this been fixed?

**Comment by mreposa** [comment]
The Simple Learning example now runs to completion.
