### ISSUE TITLE
Graph Decision example throws NoSuchElementException

### ISSUE THREAD

**Issue by mreposa** [p2t2/figaro#544]
Running MH Before...
java.util.NoSuchElementException
        at com.cra.figaro.language.Element.directContextContents(Element.scala:163)
        at com.cra.figaro.library.cache.MHCache.doNonCachingChain(MHCache.scala:122)
        at com.cra.figaro.library.cache.MHCache.apply(MHCache.scala:60)
        at com.cra.figaro.algorithm.sampling.MetropolisHastings.attemptChange(MetropolisHastings.scala:79)
        at com.cra.figaro.algorithm.sampling.MetropolisHastings.updateOne(MetropolisHastings.scala:206)
        at com.cra.figaro.algorithm.sampling.MetropolisHastings.updateMany(MetropolisHastings.scala:228)
        at com.cra.figaro.algorithm.sampling.MetropolisHastings.proposeAndUpdate(MetropolisHastings.scala:248)
        at com.cra.figaro.algorithm.sampling.MetropolisHastings.mhStep(MetropolisHastings.scala:324)
        at com.cra.figaro.algorithm.sampling.MetropolisHastings$$anonfun$doInitialize$2.apply(MetropolisHastings.scala:3
61)
        at com.cra.figaro.algorithm.sampling.MetropolisHastings$$anonfun$doInitialize$2.apply(MetropolisHastings.scala:3
61)
        at scala.collection.immutable.Range.foreach(Range.scala:166)
        at com.cra.figaro.algorithm.sampling.MetropolisHastings.doInitialize(MetropolisHastings.scala:361)
        at com.cra.figaro.algorithm.sampling.OneTimeMetropolisHastings.run(MetropolisHastings.scala:456)
        at com.cra.figaro.algorithm.OneTime$class.doStart(OneTime.scala:28)
        at com.cra.figaro.algorithm.sampling.OneTimeMetropolisHastings.doStart(MetropolisHastings.scala:445)
        at com.cra.figaro.algorithm.Algorithm$class.start(Algorithm.scala:83)
        at com.cra.figaro.algorithm.sampling.BaseUnweightedSampler.start(UnweightedSampler.scala:26)
        at com.cra.figaro.example.graph.GraphDecision$.main(GraphDecision.scala:89)
        at com.cra.figaro.example.graph.GraphDecision.main(GraphDecision.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at scala.reflect.internal.util.ScalaClassLoader$$anonfun$run$1.apply(ScalaClassLoader.scala:70)
        at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
        at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:101)
        at scala.reflect.internal.util.ScalaClassLoader$class.run(ScalaClassLoader.scala:70)
        at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:101)
        at scala.tools.nsc.CommonRunner$class.run(ObjectRunner.scala:22)
        at scala.tools.nsc.ObjectRunner$.run(ObjectRunner.scala:39)
        at scala.tools.nsc.CommonRunner$class.runAndCatch(ObjectRunner.scala:29)
        at scala.tools.nsc.ObjectRunner$.runAndCatch(ObjectRunner.scala:39)
        at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:65)
        at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:87)
        at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:98)
        at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:103)
        at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)

**Comment by bruttenberg** [comment]
Mike, is this crashing consistently or intermittently?

**Comment by bruttenberg** [comment]
Mike, I can't get this to crash

**Comment by mreposa** [comment]
It crashes consistently on my machine.

**Comment by mreposa** [comment]
This example is now running to completion on my machine:

Running GraphDecision
04:09 PM
Running MH Before...
Computing Optimal Decision...
Running MH After...
Expected Utility Before Optimization: 0.3584999999999984
Expected Utility After Optimization: 0.2699999999999986
Some Optimal Decisions:
Node 0 -> Constant(false), Constant(0.0)
Node 1 -> Constant(false), Constant(0.0)
Node 2 -> Constant(false), Constant(0.0)
Node 3 -> Constant(false), Constant(0.0)
Node 4 -> Constant(false), Constant(0.0)
Node 5 -> Constant(false), Constant(0.0)
Node 6 -> Constant(false), Constant(0.0)
Node 7 -> Constant(true), Constant(1.9244532803180912)
Node 8 -> Constant(false), Constant(0.0)
Node 9 -> Constant(false), Constant(0.0)
Node 10 -> Constant(false), Constant(0.0)
11:36 PM
