### ISSUE TITLE
why does my setup fail? 

### ISSUE THREAD

**Issue by stianSjoli** [p2t2/figaro#631]
Why does this fail?
in my sbt file:
name := "FigaroTest"

version := "1.0"

scalaVersion := "2.12.0"

libraryDependencies ++= Seq(
  "com.cra.figaro" % "figaro_2.11" % "4.0.0.0"
)

(javaversion 1.8)

in my FigaroTest.scala:

import com.cra.figaro.language._

object FigaroTest extends App {
  val hw = Constant("hello world!")
  println("hello")
}

my output:Exception in thread "main" java.lang.NoClassDefFoundError: scala/Product$class
	at com.cra.figaro.language.Name.<init>(Reference.scala:28)
	at com.cra.figaro.language.Name$.default(Reference.scala:59)
	at FigaroTest$.delayedEndpoint$FigaroTest$1(FigaroTest.scala:7)
	at FigaroTest$delayedInit$body.apply(FigaroTest.scala:6)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:378)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at FigaroTest$.main(FigaroTest.scala:6)
	at FigaroTest.main(FigaroTest.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.ClassNotFoundException: scala.Product$class
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 16 more

**Comment by stianSjoli** [comment]
I got it to work the scala compiler to be 2.11.8
