### ISSUE TITLE
AtomicNormal sampling crashes when running in Spark 

### ISSUE THREAD

**Issue by ldacosta** [p2t2/figaro#652]
I've been having random crashes on a piece of code that mixes Figaro's AtomicNormal distribution and distributed computation in Spark. A minimal example is shown here: https://gist.github.com/ldacosta/b475008959a1009a0ede64469528ce45 

The test called "direct sampling" never fails. The test called "dataset sampling" fails occasionally (ie, not consistently) with a stack trace that looks like the following: 

`org.scalatest.exceptions.GeneratorDrivenPropertyCheckFailedException: SparkException was thrown during property evaluation.
  Message: Job aborted due to stage failure: Task 15 in stage 6.0 failed 1 times, most recent failure: Lost task 15.0 in stage 6.0 (TID 84, localhost): java.lang.ArrayIndexOutOfBoundsException: 259
    at com.cra.figaro.util.HashSelectableSet.contains(SelectableSet.scala:142)
    at scala.collection.mutable.SetLike$class.add(SetLike.scala:81)
    at com.cra.figaro.util.HashSelectableSet.add(SelectableSet.scala:37)
    at com.cra.figaro.language.Universe.activate(Universe.scala:175)
    at com.cra.figaro.language.Element.<init>(Element.scala:480)
    at com.cra.figaro.library.atomic.continuous.AtomicNormal.<init>(Normal.scala:24)
    at com.cra.figaro.library.atomic.continuous.Normal$.apply(Normal.scala:140)
    at com.mediative.mpn.brain.datascience.platform.nationals.recommendations.strategy.MyCC.<init>(AtomicNormalTest.scala:13)
    at com.mediative.mpn.brain.datascience.platform.nationals.recommendations.strategy.AtomicNormalTest$$anonfun$2$$anonfun$apply$1.apply(AtomicNormalTest.scala:24)
    at com.mediative.mpn.brain.datascience.platform.nationals.recommendations.strategy.AtomicNormalTest$$anonfun$2$$anonfun$apply$1.apply(AtomicNormalTest.scala:23)
    at scala.Option.map(Option.scala:146)`

**Comment by ldacosta** [comment]
This problem disappears if I create the `AtomicNormal` distribution as `val probabilityD: AtomicNormal = Normal.apply(mean, math.pow(standardDev, 2))(Name[Double]("zzz"), new Universe())` This makes me suspect that it has something to do with the shared state `implicit var universe: Universe = new Universe` in `Object Universe`?

**Comment by bruttenberg** [comment]
Hi Luis,

Thanks for using Figaro. I don’t know the exact problem that is popping up, but in general, Figaro models are not really thread or distributed safe. There are ways to make it work in distributed environment, but generally they must be done by the modeler.

In this example, I suspect that problem is due to all of the normal distributions being created on the same universe, and their being some multi-thread problems. I don’t know what your overall goal is, but creating each Normal on a different universe will certainly avoid this issue. However, if you intend to build larger and more complex models on top of Spark, you might run into more problems (which we’re happy to discuss as well!)

Brian

+  +  +  +  +  +  +  +  +  +  +  +  +  +
Brian Ruttenberg, PhD
Senior Scientist
Decision Management Systems Division
Government Services
Charles River Analytics Inc.
617.491.3474 x730
www.cra.com<http://www.cra.com/>
