### ISSUE TITLE
Versions

### ISSUE THREAD

**Issue by toncho11** [p2t2/figaro#727]
What versions Figaro 5.0 requires: 
scala 2.12
jvm 1.8
?
I am having some problems: 

Exception in thread "main" java.lang.NoSuchMethodError: scala.Product.$init$(Lscala/Product;)V
	at com.cra.figaro.language.Name.<init>(Reference.scala:28)
	at com.cra.figaro.language.Name$.stringToName(Reference.scala:64)
	at Simulator$.<init>(Simulator.scala:11)
	at Simulator$.<clinit>(Simulator.scala)
	at Simulator.main(Simulator.scala)

It compiles, but it does not run.

**Comment by mreposa** [comment]
Figaro 5.0.0.0 cross-compiles to support both Scala 2.11.8 and 2.12.2 using Java 1.8.

**Comment by mreposa** [comment]
The stack trace is helpful, but if it's possible to post the code you're trying to run we'll be able to tell you more because we can attempt to reproduce the problem on our side and debug.

**Comment by toncho11** [comment]
Cross-compiles? It is two different fat-jars?

**Comment by toncho11** [comment]
I got the problem with Figaro 5.0

1) I needed to install Scala 2.12.x within Intellij from File->Project structure->Global Libraries. 

Unfortunately that does not change the SDK for your current project. So you need to:

2) Re-import your project. Select overwrite every time. Then click on a scala source file and at the top you will be asked to select the Scala SDK. Select 2.12.x. This is the version selected until you re-import. 

3) Go to File->Project structure->Modules->Dependencies and click on the "+". Select the Figaro 5.0 fat jar file. 

4) For Run Configuration use "Application", not "Scala script".
